import Head from "next/head";
import Navbar from "./components/Navbar";
import "./globals.scss";
import { ThemeProvider } from "next-themes";
import CustomCursor from "./components/CustomCursor";
import { useRouter } from "next/router";
export default function App({ Component, pageProps }) {

  const router = useRouter();
  const currentUrl = router.asPath;
  return (
    <ThemeProvider enableSystem={true} attribute="class">
      <Head>
        <title>Jeric Nisperos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {currentUrl == '/' ? <Navbar /> : null}
      <CustomCursor />
      {/* < /> */}
      <Component {...pageProps} />
    </ThemeProvider>
  );
}
