import Head from "next/head";
import { useTheme } from "next-themes";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faFolder, faHome, faHouseCircleCheck, faMoon, faPaperPlane, faPerson, faSun, faUser, faUserCircle } from "@fortawesome/free-solid-svg-icons";
import { motion } from "framer-motion";
import Navbar from "./components/navbar";
import lottie from 'lottie-web';
import { defineElement } from 'lord-icon-element';

defineElement(lottie.loadAnimation);

export default function Home() {
  return (
    <>
      <Head>
        <title>Jeric Nisperos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={` dark:bg-zinc-900 bg-zinc-100 min-h-[2500px] transition-colors duration-1000 ease-in-out`}>
        {/* <main className={`dark bg-zinc-900 min-h-[2500px] transition-colors duration-1000 ease-in-out`}> */}
        <div className="text-black dark:text-white">Hello </div>



      
      </main>
    </>
  );
}
