import Head from "next/head";
import { useTheme } from "next-themes";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faFolder, faHome, faHouseCircleCheck, faMoon, faPaperPlane, faPerson, faSun, faUser, faUserCircle } from "@fortawesome/free-solid-svg-icons";
import { motion } from "framer-motion";
import Navbar from "./components/Navbar";
import About from "./about";
import AboutSection from "./sections/AboutSection";
import ProjectSection from "./sections/ProjectSection";
import ContactSection from "./sections/ContactSection";
import StarBg from "./components/StarBg";
import FrontSection from "./sections/FrontSection";
import HomeSection from "./sections/HomeSection";
import { useState } from "react";
import AboutBlock from "./sections/AboutBlock";
import ProjectsBlock from "./sections/ProjectsBlock";
import ContactBlock from "./sections/ContactBlock";
export default function Home() {
  const [activeAbout, setActiveAbout] = useState("Introduction");

  const buttonVariants = {
    rest: {
      borderColor: "#fff",
      color: "#fff",
    },
    hover: {
      borderColor: "#06B6D4",
      color: "#06B6D4",
      transition: {
        duration: 0.3,
        ease: "easeInOut",
      },
    },
    active: {
      borderColor: "#fff",
      color: "#fff",
      transition: {
        duration: 0.2,
        ease: "easeInOut",
      },
    },
  };
  return (
    <>
      <Head>
        <title>Jeric Nisperos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className="cursor-default md:cursor-none scroll-smooth	">
        <div id="background-layer" className={`transition-colors duration-1000 ease-in-out`}>
          <HomeSection />
          <div className=" bg-white z-10 bg-gradient-to-b dark:from-zinc-900 dark:to-slate-800 relative duration-1000 ease-in-out">
            <AboutBlock />
          </div>
          <div className=" bg-cyan-300 z-10 bg-gradient-to-b dark:from-slate-800 dark:to-zinc-900 relative">
            <ProjectsBlock />
          </div>
          <div className="dark:bg-zinc-900 bg-white relative ">
            <ContactBlock />
          </div>
        </div>
      </main>
    </>
  );
}
